name: idez_test
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.2.0
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  mobx: ^2.5.0
  flutter_mobx: ^2.3.0
  dartz: ^0.10.1
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  mobx_codegen: ^2.4.9
  build_runner: ^2.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/montserrat/
    - assets/fonts/roboto/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
